# Generated by Django 4.1.1 on 2022-09-28 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memsite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
