# Generated by Django 4.1.1 on 2022-09-28 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memsite', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 28, 13, 50, 1, 88478, tzinfo=datetime.timezone.utc)),
        ),
    ]
